### ISSUE TITLE
Support content negotiation

### ISSUE THREAD

**Issue by pietercolpaert** [erochest/jekyll-rdfa#8]
How would we be able to do content negotiation with this library? Do we have to configure apache or nginx to do that for us?

**Comment by erochest** [comment]
This would be awesome! Unfortunately, I no of no way to do this solely from a static site. AFAIK, you have to configure your web server (apache, nginx, or whatever). Since our primary use-case is deploying to Github Pages, I haven't looked into this at all.

If there's anything we need to do to help work with the configuration of one of these servers, I'd like to hear about it, but otherwise, I think this is outside what we can implement statically.
